modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
[[mods]]
modId="harderfarther"
version="${file.jarVersion}"
displayName="Harder Farther Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harderfarther"
updateJSONURL="https://github.com/mactso/harderfarther/raw/master/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder farther Mod.'
[[dependencies.harderfarther]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.harderfarther]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="SERVER"
